# Generated by Django 4.2.3 on 2023-11-14 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('company', models.CharField(max_length=20, null=True)),
                ('view_cnt', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(max_length=100, null=True)),
                ('applier', models.CharField(default='admin', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AiRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, default=None, null=True)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_ai', to='main.ai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.ai')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.TextField(blank=True, null=True)),
                ('header_1', models.CharField(blank=True, max_length=30, null=True)),
                ('header_2', models.CharField(blank=True, max_length=30, null=True)),
                ('header_3', models.CharField(blank=True, max_length=30, null=True)),
                ('content_1', models.TextField(blank=True, null=True)),
                ('content_2', models.TextField(blank=True, null=True)),
                ('content_3', models.TextField(blank=True, null=True)),
                ('ai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='main.ai')),
            ],
        ),
        migrations.CreateModel(
            name='AiEngInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_description', models.TextField(max_length=100, null=True)),
                ('eng_title', models.CharField(max_length=30)),
                ('introduce', models.TextField(blank=True, null=True)),
                ('header_1', models.CharField(blank=True, max_length=30, null=True)),
                ('header_2', models.CharField(blank=True, max_length=30, null=True)),
                ('header_3', models.CharField(blank=True, max_length=30, null=True)),
                ('content_1', models.TextField(blank=True, null=True)),
                ('content_2', models.TextField(blank=True, null=True)),
                ('content_3', models.TextField(blank=True, null=True)),
                ('ai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_eng', to='main.ai')),
            ],
        ),
        migrations.CreateModel(
            name='AiComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_tmp', models.BooleanField(default=False, null=True)),
                ('tmp_password', models.CharField(blank=True, max_length=4, null=True)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_ai', to='main.ai')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ai',
            name='keyword',
            field=models.ManyToManyField(related_name='keywords', to='main.keyword'),
        ),
    ]
