# Generated by Django 4.2.3 on 2023-08-07 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('company', models.CharField(max_length=20, null=True)),
                ('view_cnt', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(max_length=1000, null=True)),
                ('applier', models.CharField(default='admin', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AiTempComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tmp_password', models.CharField(max_length=4)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_comments_ai', to='main.ai')),
            ],
        ),
        migrations.CreateModel(
            name='AiLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.ai')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ai')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.job')),
            ],
        ),
        migrations.CreateModel(
            name='AiComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(null=True)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_ai', to='main.ai')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ai',
            name='keyword',
            field=models.ManyToManyField(related_name='keywords', to='main.keyword'),
        ),
    ]
