# Generated by Django 4.2.3 on 2023-08-07 01:24

from django.db import migrations, models
import django.db.models.deletion
import notice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(default='admin', max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=5000)),
                ('view_cnt', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=notice.models.notification_image_upload_path)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_notification', to='notice.notification')),
            ],
        ),
    ]
