# Generated by Django 4.2.3 on 2023-11-14 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import suggestion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=5000)),
                ('url', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reflected_status', models.PositiveSmallIntegerField(choices=[(0, '대기중'), (1, '반영'), (2, '미반영')], default=0)),
                ('ai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_ai', to='main.ai')),
                ('writer', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=suggestion.models.suggestion_image_upload_path)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_suggestion', to='suggestion.suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(default='moin', max_length=10)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_suggestion', to='suggestion.suggestion')),
            ],
        ),
    ]
